--
-- Copyright CIB software GmbH and/or licensed to CIB software GmbH
-- under one or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information regarding copyright
-- ownership. CIB software licenses this file to you under the Apache License,
-- Version 2.0; you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

insert into ACT_GE_SCHEMA_LOG
values ('1500', CURRENT_TIMESTAMP, '2.2.0');



-- MODELER

CREATE TABLE MOD_ELEMENT_TEMPLATES (
    ID NVARCHAR(36) NOT NULL PRIMARY KEY,
    ACTIVE BIT DEFAULT 1,
    VERSION INT DEFAULT 1,
    TEMPLATE_ID NVARCHAR(100) NOT NULL UNIQUE,
    NAME NVARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    ORIGIN NVARCHAR(50) NOT NULL,
    CONTENT NVARCHAR(MAX),
    CREATED_AT DATETIME2 DEFAULT GETDATE() NOT NULL,
    UPDATED_AT DATETIME2 DEFAULT GETDATE() NOT NULL,
    CREATED_BY NVARCHAR(100),
    UPDATED_BY NVARCHAR(100)
);

CREATE TABLE MOD_PROCESSES_DIAGRAMS (
    ID NVARCHAR(36) NOT NULL PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    PROCESSKEY NVARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION NVARCHAR(150),
    CREATED DATETIME2,
    UPDATED DATETIME2,
    ACTIVE BIT DEFAULT 1 NOT NULL,
    TYPE NVARCHAR(50) NOT NULL,
    VERSION INT DEFAULT 1,
    DIAGRAM VARBINARY(MAX),
    UPDATED_BY NVARCHAR(100)
);

CREATE TABLE MOD_REVINFO (
    REV BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    REVTSTMP BIGINT
);

CREATE TABLE MOD_PROCESSES_DIAGRAMS_AUD (
    ID NVARCHAR(36) NOT NULL,
    NAME NVARCHAR(255),
    PROCESSKEY NVARCHAR(100),
    DESCRIPTION NVARCHAR(150),
    CREATED DATETIME2,
    UPDATED DATETIME2,
    ACTIVE BIT DEFAULT 1,
    TYPE NVARCHAR(50),
    VERSION INT DEFAULT 1,
    DIAGRAM_MOD BIT DEFAULT 0,
    DIAGRAM VARBINARY(MAX),
    UPDATED_BY NVARCHAR(100),
    REV BIGINT NOT NULL,
    REVTYPE SMALLINT,
    CONSTRAINT MOD_PK_RESOURCES_AUD PRIMARY KEY (ID, REV),
    CONSTRAINT MOD_FK_RESOURCES_AUD_REV FOREIGN KEY (REV) REFERENCES MOD_REVINFO(REV)
);

CREATE TABLE MOD_USER_SESSIONS (
    ID NVARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID NVARCHAR(100) NOT NULL,
    CREATED_AT DATETIME2 DEFAULT GETDATE() NOT NULL,
    EXPIRES_AT DATETIME2
);

CREATE TABLE MOD_DIAGRAM_USAGE (
    ID NVARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID NVARCHAR(100) NOT NULL,
    DIAGRAM_ID NVARCHAR(36) NOT NULL,
    SESSION_ID NVARCHAR(36) NOT NULL,
    OPENED_AT DATETIME2 DEFAULT GETDATE() NOT NULL,
    CLOSED_AT DATETIME2,
    CONSTRAINT MOD_FK_DIAGRAM_USAGE_DIAGRAM FOREIGN KEY (DIAGRAM_ID) REFERENCES MOD_PROCESSES_DIAGRAMS(ID) ON DELETE CASCADE,
    CONSTRAINT MOD_FK_DIAGRAM_USAGE_SESSION FOREIGN KEY (SESSION_ID) REFERENCES MOD_USER_SESSIONS(ID) ON DELETE CASCADE
);

CREATE TABLE MOD_FORMS (
    ID NVARCHAR(36) NOT NULL PRIMARY KEY,
    DESCRIPTION NVARCHAR(150),
    CREATED DATETIME2,
    UPDATED DATETIME2,
    ACTIVE BIT DEFAULT 1 NOT NULL,
    FORM_SCHEMA VARBINARY(MAX) NOT NULL,
    FORMID NVARCHAR(100) NOT NULL UNIQUE,
    VERSION INT DEFAULT 1,
    UPDATED_BY NVARCHAR(100)
);

CREATE TABLE MOD_FORM_USAGE (
    ID NVARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID NVARCHAR(100) NOT NULL,
    FORM_ID NVARCHAR(36) NOT NULL,
    SESSION_ID NVARCHAR(36) NOT NULL,
    OPENED_AT DATETIME2 DEFAULT GETDATE() NOT NULL,
    CLOSED_AT DATETIME2,
    CONSTRAINT MOD_FK_FORM_USAGE_FORM FOREIGN KEY (FORM_ID) REFERENCES MOD_FORMS(ID) ON DELETE CASCADE,
    CONSTRAINT MOD_FK_FORM_USAGE_SESSION FOREIGN KEY (SESSION_ID) REFERENCES MOD_USER_SESSIONS(ID) ON DELETE CASCADE
);

CREATE TABLE CHAT_MESSAGES (
    ID           NVARCHAR(36)  NOT NULL,
    ROOM_ID      NVARCHAR(255) NOT NULL,
    ELEMENT_ID   NVARCHAR(255),
    USER_ID      NVARCHAR(255) NOT NULL,
    DISPLAY_NAME NVARCHAR(255),
    CONTENT      NVARCHAR(MAX) NOT NULL,
    CREATED_AT   DATETIME2     NOT NULL,
    EDITED_AT    DATETIME2,
    CONSTRAINT CHAT_PK_MESSAGES PRIMARY KEY (ID)
);

CREATE INDEX CHAT_IDX_MESSAGES_ROOM_CREATED    ON CHAT_MESSAGES (ROOM_ID, CREATED_AT);
CREATE INDEX CHAT_IDX_MESSAGES_ROOM_EL_CREATED ON CHAT_MESSAGES (ROOM_ID, ELEMENT_ID, CREATED_AT);