--
-- Copyright CIB software GmbH and/or licensed to CIB software GmbH
-- under one or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information regarding copyright
-- ownership. CIB software licenses this file to you under the Apache License,
-- Version 2.0; you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
CREATE TABLE IF NOT EXISTS MOD_ELEMENT_TEMPLATES (
    ID VARCHAR(36) PRIMARY KEY,
    ACTIVE TINYINT(1) DEFAULT 1,
    VERSION INT(11) DEFAULT 1,
    TEMPLATE_ID VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION LONGTEXT,
    ORIGIN VARCHAR(50) NOT NULL,
    CONTENT LONGTEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_FOLDERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    PARENT_ID VARCHAR(36),
    NAME VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP NULL,
    CREATED_BY VARCHAR(100),
    UPDATED TIMESTAMP NULL,
    UPDATED_BY VARCHAR(100),
    CONSTRAINT MOD_UK_FOLDERS_PARENT_NAME UNIQUE (PARENT_ID, NAME),
    CONSTRAINT MOD_FK_FOLDERS_PARENT FOREIGN KEY (PARENT_ID) REFERENCES MOD_FOLDERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX MOD_IDX_FOLDERS_PARENT ON MOD_FOLDERS (PARENT_ID);

CREATE TABLE IF NOT EXISTS MOD_PROCESSES_DIAGRAMS (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255),
    PROCESSKEY VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(150),
    CREATED TIMESTAMP NULL,
    UPDATED TIMESTAMP NULL,
    ACTIVE TINYINT(1) DEFAULT 1 NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    VERSION INT DEFAULT 1,
    DIAGRAM LONGBLOB,
    UPDATED_BY VARCHAR(100) NULL,
    FOLDER_ID VARCHAR(36),
    CONSTRAINT MOD_FK_DIAGRAMS_FOLDER FOREIGN KEY (FOLDER_ID) REFERENCES MOD_FOLDERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_REVINFO (
    REV BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    REVTSTMP BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_PROCESSES_DIAGRAMS_AUD (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255),
    PROCESSKEY VARCHAR(100),
    DESCRIPTION VARCHAR(150),
    CREATED TIMESTAMP NULL DEFAULT NULL,
    UPDATED TIMESTAMP NULL DEFAULT NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    TYPE VARCHAR(50),
    VERSION INT(11) DEFAULT 1,
    DIAGRAM_MOD TINYINT(1) DEFAULT 0,
    DIAGRAM LONGBLOB,
    UPDATED_BY VARCHAR(100),
    REV BIGINT NOT NULL,
    REVTYPE SMALLINT,
    CONSTRAINT MOD_PK_RESOURCES_AUD PRIMARY KEY (ID, REV),
    CONSTRAINT MOD_FK_RESOURCES_AUD_REV FOREIGN KEY (REV) REFERENCES MOD_REVINFO(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_USER_SESSIONS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_DIAGRAM_USAGE (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    DIAGRAM_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36) NOT NULL,
    OPENED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLOSED_AT TIMESTAMP,
    CONSTRAINT MOD_FK_DIAGRAM_USAGE_DIAGRAM FOREIGN KEY (DIAGRAM_ID) REFERENCES MOD_PROCESSES_DIAGRAMS(ID) ON DELETE CASCADE,
    CONSTRAINT MOD_FK_DIAGRAM_USAGE_SESSION FOREIGN KEY (SESSION_ID) REFERENCES MOD_USER_SESSIONS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_FORMS (
    ID VARCHAR(36) PRIMARY KEY,
    DESCRIPTION VARCHAR(150),
    CREATED TIMESTAMP NULL,
    UPDATED TIMESTAMP NULL,
    ACTIVE TINYINT(1) DEFAULT 1 NOT NULL,
    FORM_SCHEMA LONGBLOB NOT NULL,
    FORMID VARCHAR(100) NOT NULL UNIQUE,
    VERSION INT(11) DEFAULT 1,
    UPDATED_BY VARCHAR(100) NULL,
    FOLDER_ID VARCHAR(36),
    CONSTRAINT MOD_FK_FORMS_FOLDER FOREIGN KEY (FOLDER_ID) REFERENCES MOD_FOLDERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_FORMS_AUD (
    ID VARCHAR(36) NOT NULL,
    DESCRIPTION VARCHAR(150),
    CREATED TIMESTAMP NULL DEFAULT NULL,
    UPDATED TIMESTAMP NULL DEFAULT NULL,
    ACTIVE TINYINT(1) DEFAULT 1,
    FORM_SCHEMA LONGBLOB,
    FORMID VARCHAR(100),
    VERSION INT(11) DEFAULT 1,
    SCHEMA_MOD TINYINT(1) DEFAULT 0,
    UPDATED_BY VARCHAR(100),
    REV BIGINT NOT NULL,
    REVTYPE SMALLINT,
    CONSTRAINT MOD_PK_FORMS_AUD PRIMARY KEY (ID, REV),
    CONSTRAINT MOD_FK_FORMS_AUD_REV FOREIGN KEY (REV) REFERENCES MOD_REVINFO(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MOD_FORM_USAGE (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    FORM_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36) NOT NULL,
    OPENED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLOSED_AT TIMESTAMP,
    CONSTRAINT MOD_FK_FORM_USAGE_FORM FOREIGN KEY (FORM_ID) REFERENCES MOD_FORMS(ID) ON DELETE CASCADE,
    CONSTRAINT MOD_FK_FORM_USAGE_SESSION FOREIGN KEY (SESSION_ID) REFERENCES MOD_USER_SESSIONS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CHAT_MESSAGES (
    ID           VARCHAR(36)  NOT NULL,
    ROOM_ID      VARCHAR(255) NOT NULL,
    ELEMENT_ID   VARCHAR(255),
    USER_ID      VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255),
    CONTENT      LONGTEXT     NOT NULL,
    CREATED_AT   DATETIME(6)  NOT NULL,
    EDITED_AT    DATETIME(6),
    DELETED_AT   DATETIME(6),
    CONSTRAINT CHAT_PK_MESSAGES PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX CHAT_IDX_MESSAGES_ROOM_CREATED    ON CHAT_MESSAGES (ROOM_ID, CREATED_AT);
CREATE INDEX CHAT_IDX_MESSAGES_ROOM_EL_CREATED ON CHAT_MESSAGES (ROOM_ID, ELEMENT_ID, CREATED_AT);

CREATE TABLE CHAT_PRESENCE (
    ROOM_ID      VARCHAR(255) NOT NULL,
    USER_ID      VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255),
    LAST_SEEN    DATETIME(6)  NOT NULL,
    CONSTRAINT CHAT_PK_PRESENCE PRIMARY KEY (ROOM_ID, USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Notifications: messages administrators publish to logged-in webclient users (CIB7-1867)
CREATE TABLE NOTIFICATIONS (
    ID           VARCHAR(36)   NOT NULL,
    TITLE        VARCHAR(255)  NOT NULL,
    BODY         LONGTEXT NOT NULL,
    SEVERITY     VARCHAR(20)   NOT NULL,
    AUDIENCE     VARCHAR(20)   NOT NULL,
    VALID_FROM   DATETIME(6) NOT NULL,
    VALID_TO     DATETIME(6),
    DISMISSIBLE  TINYINT(1) DEFAULT 1 NOT NULL,
    LINK         VARCHAR(1000),
    ACTIVE       TINYINT(1) DEFAULT 0 NOT NULL,
    CREATED_AT   DATETIME(6) NOT NULL,
    CREATED_BY   VARCHAR(255)  NOT NULL,
    UPDATED_AT   DATETIME(6),
    UPDATED_BY   VARCHAR(255),
    CONSTRAINT NOTIF_PK_NOTIFICATIONS PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX NOTIF_IDX_NOTIFICATIONS_ACTIVE ON NOTIFICATIONS (ACTIVE, VALID_FROM, VALID_TO);

CREATE TABLE NOTIFICATION_GROUPS (
    NOTIFICATION_ID VARCHAR(36)  NOT NULL,
    GROUP_ID        VARCHAR(255) NOT NULL,
    CONSTRAINT NOTIF_PK_GROUPS PRIMARY KEY (NOTIFICATION_ID, GROUP_ID),
    CONSTRAINT NOTIF_FK_GROUPS_NOTIFICATION FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATIONS (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX NOTIF_IDX_GROUPS_GROUP ON NOTIFICATION_GROUPS (GROUP_ID);
