/*
 * Copyright CIB software GmbH and/or licensed to CIB software GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership. CIB software licenses this file to you under the Apache License,
 * Version 2.0; you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.cibseven.connect.ai.agent.impl;

import dev.langchain4j.store.memory.chat.ChatMemoryStore;
import dev.langchain4j.store.memory.chat.InMemoryChatMemoryStore;

/**
 * JVM-wide singleton holder for the {@link ChatMemoryStore} used by the agent
 * connector. Each connector invocation that activates chat memory looks up its
 * memory by {@code memoryId} in this shared store, allowing a BPMN process to
 * carry conversation history across service-task invocations — typically across
 * a human-feedback user task in between.
 *
 * <p>The default backing store is a {@link ProcessVariableChatMemoryStore}, which
 * persists the conversation as a process variable, so memory survives an engine
 * restart and is visible to every node of a clustered deployment. A
 * {@code memoryId} is therefore scoped to one process instance. Outside an engine
 * context (tests, embedded use) it falls back to an {@link InMemoryChatMemoryStore}.
 *
 * <p>Deployments needing different semantics — e.g. memory shared across process
 * instances — can replace the store at startup via {@link #setStore(ChatMemoryStore)},
 * which takes precedence over the default. Mind that a store outside the engine
 * (Redis, …) does not take part in the job transaction, so a failed and retried
 * agent task can append the same turn twice.
 *
 * <p>The memory is keyed by an arbitrary {@code Object} (in practice a
 * {@code String}) — typically the process instance id or a UUID generated by
 * the connector on the first call.
 */
public final class AgentChatMemoryStore {

  private static volatile ChatMemoryStore store =
      new ProcessVariableChatMemoryStore(new InMemoryChatMemoryStore());

  private AgentChatMemoryStore() {
    // utility holder
  }

  /** Returns the currently configured shared {@link ChatMemoryStore}. */
  public static ChatMemoryStore getStore() {
    return store;
  }

  /**
   * Replaces the shared {@link ChatMemoryStore} and takes precedence over the
   * default. Intended for application startup wiring (e.g. a store shared across
   * process instances) and for tests that need to isolate state.
   */
  public static void setStore(ChatMemoryStore newStore) {
    if (newStore == null) {
      throw new IllegalArgumentException("ChatMemoryStore must not be null");
    }
    store = newStore;
  }

  /**
   * Convenience helper to forget the chat history for a given memory id —
   * mirrors {@link ChatMemoryStore#deleteMessages(Object)} on the current store.
   * Rarely needed with the default store, where the memory variable dies with
   * the process instance.
   */
  public static void clear(Object memoryId) {
    store.deleteMessages(memoryId);
  }

}
