/*
 * Copyright CIB software GmbH and/or licensed to CIB software GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership. CIB software licenses this file to you under the Apache License,
 * Version 2.0; you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.cibseven.connect.ai.agent.impl;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import dev.langchain4j.store.memory.chat.ChatMemoryStore;
import dev.langchain4j.store.memory.chat.InMemoryChatMemoryStore;

/**
 * JVM-wide singleton holder for the {@link ChatMemoryStore} used by the agent
 * connector. Each connector invocation that activates chat memory looks up its
 * memory by {@code memoryId} in this shared store, allowing a BPMN process to
 * carry conversation history across service-task invocations — typically across
 * a human-feedback user task in between.
 *
 * <p>Which store is used by default is decided here, once, from
 * {@value #PERSISTENT_STORE_PROPERTY}: a {@link ProcessVariableChatMemoryStore}
 * that persists the conversation as a process variable — surviving an engine
 * restart and visible to every node of a clustered deployment, with a
 * {@code memoryId} scoped to one process instance — or, when the flag is
 * {@code false}, a JVM-local {@link InMemoryChatMemoryStore}.
 *
 * <p>Deployments needing different semantics — e.g. memory shared across process
 * instances — can replace the store at startup via {@link #setStore(ChatMemoryStore)},
 * which takes precedence over the default. Mind that a store outside the engine
 * (Redis, …) does not take part in the job transaction, so a failed and retried
 * agent task can append the same turn twice.
 *
 * <p>The memory is keyed by an arbitrary {@code Object} (in practice a
 * {@code String}) — typically the process instance id or a UUID generated by
 * the connector on the first call.
 */
public final class AgentChatMemoryStore {

  private static final Logger LOG = LoggerFactory.getLogger(AgentChatMemoryStore.class);

  /**
   * Selects the default store: {@code true} (the default) persists chat memory as
   * a process variable, {@code false} keeps it in a JVM-local map — single node
   * only, lost on restart.
   */
  static final String PERSISTENT_STORE_PROPERTY =
      "cibseven.connect.ai-agent.chatMemoryVariable.enabled";

  /** Environment-variable fallback for {@link #PERSISTENT_STORE_PROPERTY}. */
  static final String PERSISTENT_STORE_ENV_VAR =
      "CIBSEVEN_CONNECT_AI_AGENT_CHAT_MEMORY_VARIABLE_ENABLED";

  private static volatile ChatMemoryStore store = resolveDefaultStore();

  private AgentChatMemoryStore() {
    // utility holder
  }

  /**
   * Builds the default store from the deployment configuration. Resolved once at
   * class initialisation: the selection is startup configuration (JVM argument or
   * environment variable), not something that may flip while conversations are in
   * flight. Package-private so tests can exercise the selection without relying on
   * class-load timing.
   */
  static ChatMemoryStore resolveDefaultStore() {
    boolean persistent = AgentChatListener.resolveBooleanFlag(
        PERSISTENT_STORE_PROPERTY, PERSISTENT_STORE_ENV_VAR, true);
    if (!persistent) {
      LOG.warn("AI Agent connector: persistent chat memory is DISABLED (system property {} or "
          + "env var {} = false). Memory is kept in a JVM-local store, so conversations are lost "
          + "on engine restart and are NOT shared across engine replicas — a task resumed on "
          + "another node will start over.",
          PERSISTENT_STORE_PROPERTY, PERSISTENT_STORE_ENV_VAR);
      return new InMemoryChatMemoryStore();
    }
    return new ProcessVariableChatMemoryStore();
  }

  /** Returns the currently configured shared {@link ChatMemoryStore}. */
  public static ChatMemoryStore getStore() {
    return store;
  }

  /**
   * Replaces the shared {@link ChatMemoryStore} and takes precedence over the
   * default. Intended for application startup wiring (e.g. a store shared across
   * process instances) and for tests that need to isolate state.
   */
  public static void setStore(ChatMemoryStore newStore) {
    if (newStore == null) {
      throw new IllegalArgumentException("ChatMemoryStore must not be null");
    }
    store = newStore;
  }

  /**
   * Forgets the chat history for a given memory id — mirrors
   * {@link ChatMemoryStore#deleteMessages(Object)} on the current store. Rarely
   * needed with the default store, where the memory variable dies with the
   * process instance anyway.
   *
   * <p><b>Contract:</b> with the default {@link ProcessVariableChatMemoryStore}
   * the conversation lives in a process variable, which is only reachable from a
   * thread that carries a {@code BpmnExecutionContext} — that is, from inside an
   * engine command. Called from an administration or application thread it would
   * reach only the store's internal fallback buffer and leave the variable in the
   * database. Rather than reporting success in that case, this method throws.
   *
   * @throws AgentConnectorException when the current thread cannot reach the
   *     persisted conversation. Call it from within an engine command (for
   *     example a {@code JavaDelegate} or an execution listener), or delete the
   *     process instance, which removes the variable with it.
   */
  public static void clear(Object memoryId) {
    ChatMemoryStore current = store;
    if (current instanceof ProcessVariableChatMemoryStore
        && !((ProcessVariableChatMemoryStore) current).deletesPersistently()) {
      throw new AgentConnectorException(
          "Cannot clear chat memory '" + memoryId + "': the conversation is stored as a process "
          + "variable, and the current thread has no BpmnExecutionContext, so the delete would "
          + "only affect an in-memory fallback buffer and leave the variable in the database. "
          + "Call this from inside an engine command, or delete the process instance instead.");
    }
    current.deleteMessages(memoryId);
  }

}
