name: Set Version Labels

on:
  issues:
    types:
      - closed

jobs:
  call-reusable-flow:
    uses: cibseven/automation-platform-github-actions/.github/workflows/set-version-labels.yml@main
    secrets: inherit
